### ISSUE TITLE
Latest version results in 500 error

### ISSUE THREAD

**Issue by scottbuscemi** [daylifemike/photomosaic-for-wordpress#1]
"PHP Parse error: syntax error, unexpected 'if' (T_IF) in /wp-content/plugins/photomosaic-for-wordpress/admin/vendor/github-updater/src/GitHub_Updater/Base.php on line 318"

Installing the latest version results in the above error.

**Comment by daylifemike** [comment]
fixed in 944ab465fb1ce82bfd722c30a1d3cd88fc6fc52f
